/**
 * Builders for `/sitemap.xml`, `/robots.txt` and `/llms.txt`.
 *
 * The site has never had any of the three. Every URL below the homepage was
 * discoverable only by following links, and the homepage links to nothing.
 *
 * Pure and side-effect free, so they can be tested without running a build.
 */

import { SITE_DESCRIPTION, SITE_NAME, isPrivateRoute, siteUrl } from './site.mjs'

/** The homepage is the one URL that is not a piece of content. */
const HOME = { changefreq: 'weekly', priority: 1.0 }
const PAGE = { changefreq: 'monthly', priority: 0.7 }

/**
 * Escape the five XML predefined entities.
 *
 * A sitemap that is not well-formed XML is rejected whole rather than in part,
 * so one apostrophe in one title would cost the site every URL in the file.
 */
export function escapeXml(value) {
  return String(value)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&apos;')
}

/**
 * The pages worth listing, in a stable order.
 *
 * Syndicated copies are left out: their canonical points somewhere else, and
 * asking a crawler to index a URL that disclaims itself wastes the request.
 * Machinery routes are left out for the reason they carry `noindex`.
 */
export function listablePages(pages = []) {
  return pages
    .filter((page) => !isPrivateRoute(page.path))
    .filter((page) => !page.canonical)
    .sort((a, b) => a.path.localeCompare(b.path))
}

/** Render `/sitemap.xml`. */
export function sitemapXml(pages = []) {
  const entries = [
    { loc: siteUrl('/'), ...HOME },
    // `lastmod` is Drupal's own `changed` timestamp, so it is a fact about the
    // content. Taking it from a file's mtime instead would claim every page
    // changed on every build, which is worse than claiming nothing.
    ...listablePages(pages).map((page) => ({
      loc: siteUrl(page.path),
      lastmod: page.changed ? String(page.changed).slice(0, 10) : undefined,
      ...PAGE,
    })),
  ]

  const urls = entries.map((entry) =>
    [
      '  <url>',
      `    <loc>${escapeXml(entry.loc)}</loc>`,
      ...(entry.lastmod ? [`    <lastmod>${entry.lastmod}</lastmod>`] : []),
      `    <changefreq>${entry.changefreq}</changefreq>`,
      `    <priority>${entry.priority.toFixed(1)}</priority>`,
      '  </url>',
    ].join('\n')
  )

  return [
    '<?xml version="1.0" encoding="UTF-8"?>',
    '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">',
    ...urls,
    '</urlset>',
    '',
  ].join('\n')
}

/** Render `/robots.txt`. */
export function robotsTxt() {
  return [
    `# ${SITE_NAME}`,
    '#',
    '# A demonstration site. Everything a reader can see is meant to be indexed;',
    '# the parts that are not are the ones only a signed-in author can use.',
    '',
    'User-agent: *',
    'Allow: /',
    '',
    '# The authoring tool and the sign-in redirect. Neither renders anything to',
    '# read, and the tool does nothing at all for someone who is not signed in.',
    '# Both also carry `noindex`; this saves a crawler the fetch.',
    'Disallow: /authoring',
    'Disallow: /callback',
    '',
    '# Build output of the static export. It serves the same content the HTML',
    '# routes already do, so indexing it splits one page across two URLs.',
    'Disallow: /_nuxt/',
    '',
    `Sitemap: ${siteUrl('/sitemap.xml')}`,
    '',
  ].join('\n')
}

/**
 * Render `/llms.txt`, the plain-text index described at https://llmstxt.org.
 *
 * Not a second sitemap. A sitemap is URLs with no descriptions, for a crawler
 * deciding when to come back. This says what each page is, for an assistant
 * deciding which one answers the question in front of it.
 */
export function llmsTxt(pages = []) {
  const listed = listablePages(pages)
  return [
    `# ${SITE_NAME}`,
    '',
    `> ${SITE_DESCRIPTION}`,
    '',
    'The site is generated by Nuxt and served as static files from GitHub Pages.',
    'There is no Drupal running behind it. A backend is started on demand when',
    'someone signs in to write, and it is gone again once the change has been',
    'committed back to the repository.',
    '',
    '## Pages',
    '',
    ...(listed.length
      ? listed.map(
          (page) =>
            `- [${page.title || page.path}](${siteUrl(page.path)})${
              page.description ? `: ${page.description}` : ''
            }`
        )
      : ['- No content published yet.']),
    '',
  ].join('\n')
}
